name: Issue Info
on:
  issues:
    types: [opened, closed, edited]
  workflow_dispatch:
jobs:
    issue_details:
        runs-on: ubuntu-latest
        steps:
        - name: print event details
          run: |
            echo "Issue Title: ${{ github.event.issue.title }}"
            echo "Issue Number: ${{ github.event.issue.number }}"
            echo "Issue State: ${{ github.event.issue.state }}"
            echo "Created By: ${{ github.event.issue.user.login }}"
            echo "Issue Body: ${{ github.event.issue.body }}"

